# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Build and Deploy
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: 'x64'

      - name: Install Python Dependency
        run: |
          pip3 install -U -r requirements.txt

      - name: Calculate
        run: |
          bash main.sh

      - name: Release Index
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: site
          clean: true

      - name: Invoke workflow in XCPCIO-rating with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update And Commit
          repo: XCPCIO/XCPCIO-rating
          token: ${{ secrets.GH_TOKEN }}